# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 'latest'
    checkLatest: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 'latest'
    includePreviewVersions: true

- task: UseNode@1
  inputs:
    version: 'latest'
    checkLatest: true