//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JesseHouwing.CheckinPolicies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JesseHouwing.CheckinPolicies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy warns the user when a checkin contains changes in multiple branches..
        /// </summary>
        internal static string PolicyDescription {
            get {
                return ResourceManager.GetString("PolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss warning?.
        /// </summary>
        internal static string PolicyDismissMessage {
            get {
                return ResourceManager.GetString("PolicyDismissMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are checking in into multiple projects and/or branches.
        /// </summary>
        internal static string PolicyDismissTitle {
            get {
                return ResourceManager.GetString("PolicyDismissTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Branches.
        /// </summary>
        internal static string PolicyType {
            get {
                return ResourceManager.GetString("PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When working in a large workspace it might happen that you have made changes in multiple branches at the same time. When checking into multiple branches in one checkin, it may be harder to track the changes and merges can result in unexpected behavior..
        /// </summary>
        internal static string PolicyTypeDescription {
            get {
                return ResourceManager.GetString("PolicyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking into multiple branches at the same time.
        /// </summary>
        internal static string PolicyWarningBranches {
            get {
                return ResourceManager.GetString("PolicyWarningBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking into multiple projects at the same time.
        /// </summary>
        internal static string PolicyWarningProjects {
            get {
                return ResourceManager.GetString("PolicyWarningProjects", resourceCulture);
            }
        }
    }
}
